# Generated by Django 4.0.5 on 2022-06-12 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Domashno', '0003_alter_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='blockedUser',
            field=models.ManyToManyField(blank=True, null=True, related_name='blocked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
