# Generated by Django 4.0.5 on 2022-06-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Domashno', '0004_alter_author_blockeduser_alter_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='lastChange',
            field=models.DateField(),
        ),
    ]
